name: Inject and run
on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      API_TOKEN:     ${{ secrets.API_TOKEN }}
      API_ENDPOINT:  ${{ vars.API_ENDPOINT }} # optional
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      # Only needed if you use YAML files in `structured`
      # - run: pip install --disable-pip-version-check --no-cache-dir pyyaml

      - name: Inject values
        run: |
          python tools/inject.py --mapping tools/mapping.json --require-all

      - name: Run
        run: python app.py
