name: Inject JSON Secrets
on: [push, workflow_dispatch]

jobs:
  inject:
    runs-on: ubuntu-latest
    env:
      DB_USER:     ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      API_KEY:     ${{ secrets.API_KEY }}
      API_ENDPOINT: ${{ vars.API_ENDPOINT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Inject
        run: |
          python scripts/inject_secrets.py \
            --file config.json \
            --template config.template.json \
            --map tools/config/mapping.json
      # Optional: upload without printing secrets
      - uses: actions/upload-artifact@v4
        with:
          name: config-json
          path: config.json
